### ISSUE TITLE
From bundler: "Unfortunately, the gem rake-hooks (1) has an invalid gemspec."

### ISSUE THREAD

**Issue by mattscilipoti** [guillermo/rake-hooks#10]
When I attempt to `bundle update rails`, I receive this error:
"Unfortunately, the gem rake-hooks (1) has an invalid gemspec. As a result, Bundler cannot install this Gemfile. Please ask the gem author to yank the bad version to fix this issue. For more information, see http://bit.ly/syck-defaultkey."
- RUBYGEMS VERSION: 1.8.19
- RUBY VERSION: 1.9.3 (2011-10-30 patchlevel 0) [x86_64-darwin11.2.0]

I checked that page and I didn't see how that related to this project.  I have the latest rubygems (1.8.19).  Any ideas?

**Comment by kaineer** [comment]
Same here, running `bundle install` in my project.
- RUBYGEMS_VERSION: 1.8.21
- RUBY_VERSION: ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]

**Comment by dayyan** [comment]
I solved this problem by using an earlier verson of bundler, specifically 1.0.21.

**Comment by soulcutter** [comment]
You can also fix this by doing "bundle install --full-index" however the offending version(s) should really be pulled from rubygems, because this problem isn't going to go away otherwise.

http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem

Side-note: this --full-index workaround doesn't work with bundle update.

**Comment by szymon-jez** [comment]
@soulcutter thanks + 1 up vote for the idea to remove the published offending version(s)

**Comment by stanislaw** [comment]
The same here:

RUBYGEMS: 1.8.19
RUBY - 1.9.3-p125

**Comment by mattscilipoti** [comment]
My investigation indicates that version 1 of rake-hooks is causing the issue.  I didn't realize, until I was debugging, that the "1" in the error message "rake-hooks (1)" was a version number.  The lack of a ".0", as in "1.0", threw me off.

It does seem kind of strange that version "1" is affecting us even if we are specifying version 1.2.3 OR installing a local package. But... the Rubygems guys are recommending we yank the offending version from rubygems.org.  

Please yank version "1".
http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem

**Comment by guillermo** [comment]
WOW!!! Seems like a totally wired bug !

I just yank version 1. Can you please try again? I was not able to reproduce this problem.

**Comment by mattscilipoti** [comment]
Thanks!  That seems to have done it.  Even my Travis CI is passing.

"I was unable to reproduce this problem":
Interesting.  It is causing your travis builds to break too: http://travis-ci.org/#!/guillermo/rake-hooks/jobs/1100996.  These should pass after your next commit, even if you simply change your readme.
