### ISSUE TITLE
undefined method `after`

### ISSUE THREAD

**Issue by brendon** [guillermo/rake-hooks#4]
I've included rake-hooks in my rails 3.1.1 Gemfile for all environments and have created a rake file in lib/ exactly as your example on the homepage and just get:

```
rake aborted!
undefined method `after' for main:Object
```

What could I be doing wrong? I'm requiring the library at the top of the rake file.

**Comment by guillermo** [comment]
I will have a look when coming back home.

Can you post your Gemfile and also say which version of bundler (bundle --version) are you using?

**Comment by brendon** [comment]
Thanks Guillermo :)

My bundler version is 1.0.21 and here's the Gemfile:

https://gist.github.com/1365258

**Comment by guillermo** [comment]
Sorry by delay.

This issue should be fixed.

If you have time, please upgrade to the new version.

**Comment by brendon** [comment]
Hi Guillermo, thanks for following this up for me. I managed to work around my issue with normal rake overloading techniques but will give it a go next time it comes up :)

Have a great day! :)

Brendon
